
services:
  DockerProject:
    image: myapp:0.0.1
    ports:
      - 8080:8080
    environment:
      DB_URL: "jdbc:mysql://mysqldb/SchoolDb?useSSL=false&useTimezone=true&serverTimezone=UTC"
      DB_USERNAME: "root"
      DB_PASSWORD: "SqlRabia2424"
      DB_HOST: "mysqldb"
      DB_PORT: 3306
    depends_on:
      mysqldb:
        condition: service_healthy

  mysqldb:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: SqlRabia2424
      MYSQL_DATABASE: SchoolDb
      MYSQL_USER: user
      MYSQL_PASSWORD: SqlRabia2424
      MYSQL_CONNECT_TIMEOUT: 600
      MYSQL_WAIT_TIMEOUT: 28800
      MYSQL_INTERACTIVE_TIMEOUT: 28800
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5